#! /bin/sh

/usr/bin/nvidia-composition-pipeline.sh

sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor DVI-D-0 -d IV V VI VII 
#bspc monitor DP-1 -d I II III
#bspc monitor HDMI-0 -d VIII IX X

## While loop to detect and config displays
/usr/bin/bspwm_workspaces.sh &

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


## Polybar
/usr/bin/polybar-launch.sh &
#polybar center &
#polybar left &
#polybar right &


## Autostart
/usr/bin/nm-applet &
/usr/bin/autokey &
/usr/bin/slack &
/usr/bin/telegram-desktop &
/usr/bin/pasystray &
autokey-gtk &
/usr/bin/xfce4-power-manager &
/usr/bin/nitrogen --restore &
/usr/bin/parcellite &

bspc rule -a Slack sticky=on state=floating hidden=on
bspc rule -a TelegramDesktop sticky=on state=floating hidden=on
bspc rule -a zoom sticky=on state=floating hidden=on
bspc rule -a crx_idbejgmlldkhoiogoknpihhhbimbikdo sticky=on state=floating hidden=on
